//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollment
    {
        public string courseId { get; set; }
        public string courseName { get; set; }
        public string studentId { get; set; }
        public string studentName { get; set; }
        public string semester { get; set; }
        public System.DateTime enrollmentDate { get; set; }
    }
}
